name = "wasm-call-ts-sample"
main = "src/index.ts"
compatibility_date = "2024-10-27"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "MY_KV"
id = "ce12850a87e743d19fd008a5b32cc336"

[[d1_databases]]
binding = "DB" # Ruby/JSからアクセスしやすいようにbinding名をDBに変更します
database_name = "wasm-d1-test"
database_id = "5f755bff-6d38-4575-8ef5-6a0ed4861503"

[[rules]]
type = "Text"
globs = ["**/*.rb"]
fallthrough = true
